### ISSUE TITLE
[BUG] Split of Undefined 

### ISSUE THREAD

**Issue by phaticusthiccy** [LuanRT/google-this#2]
https://github.com/LuanRT/google-this/blob/33d90d9a45e0350a6f20080ac41e6e65efc0d063/googleThis.js#L23

https://github.com/LuanRT/google-this/blob/33d90d9a45e0350a6f20080ac41e6e65efc0d063/googleThis.js#L24

https://github.com/LuanRT/google-this/blob/33d90d9a45e0350a6f20080ac41e6e65efc0d063/googleThis.js#L25

https://github.com/LuanRT/google-this/blob/33d90d9a45e0350a6f20080ac41e6e65efc0d063/googleThis.js#L26

**Comment by phaticusthiccy** [comment]
It always return `TypeError: Cannot read property 'split' of undefined`

I'll be glad if you check :)

**Comment by LuanRT** [comment]
> It always return `TypeError: Cannot read property 'split' of undefined`
> 
> I'll be glad if you check :)

Hello there, my apologies for the late reply.
I've been investigating this problem since last week and found out Google has changed some things in the search results page, therefore causing this module to break.

I rewrote the code (mostly because of that and because it was not very efficient) and got it to work again.
Many things have changed and there are some new features, so if you are still willing to use this module you may want to check out the readme for instructions.

**Comment by phaticusthiccy** [comment]
Thanks @LuanRT 
You did an perfect job! And absolutely yes, ı will use your repository in [WhatsAsena](www.github.com/phaticusthiccy/WhatsAsenaDuplicated)
I've been looking for something like this for a long time and ı found this repo. Thanks for codding this 😊
Many people will be grateful to you :) (Abouth 15K user hehe)

Now this issues are solved. I m going to close this.
